<?php $state = trim($this->getRequest()->getParam('check'),'/') ?>
<?php if($state == "error"):?>
    <input type="hidden" id="state" value="error">
<?php endif;?>
<?php
//    echo "<pre>";
//var_dump($this->isShow());
//echo "</pre>";
//die();
?>
<?php if($this->isShow()): ?>
    <div id="magestore-form-solutionpartner" >
        <center class="bottom-form">
            <div class="solutionpartner-registration-form fieldset" style="text-align:center;">
                <h2 class="legend"><?php echo $this->__('Solution Partner Registration Form') ?></h2>
                <?php
                $action = str_replace(array('http://', 'https://'), array('', ''), $this->getPostActionUrl());
                if((!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
                    || $_SERVER['SERVER_PORT'] == 443)
                    $action = 'https://'.$action;
                else
                    $action = 'http://'.$action;
                ?>
                <form action="<?php echo $action ?>" method="post" id="solutionpartner-registration-form" enctype="multipart/form-data">
                    <center>
                        <div class="show_message" style="text-align:left; width: 98%; margin-top: 10px;">
                            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                        </div>
                        <br/>
                        <ul class="form-list-register" style="text-align:left;">
                            <li class="row">
                                <div class="col-sm-6">
                                    <label for="solutionpartner:name" class="required"><?php echo $this->__('Name') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="name" value="<?php echo $this->htmlEscape($this->getFormData()->getName()) ?>" title="<?php echo $this->__('Name') ?>" id="solutionpartner:name" class="input-text required-entry" required/>
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <label for="solutionpartner:email" class="required"><?php echo $this->__('Email') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="email" readonly value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email') ?>" id="solutionpartner:email" class="input-text required-entry" required/>
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-12">
                                    <label for="solutionpartner:phone" class="required right-l"><?php echo $this->__('Phone') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="phone" value="<?php echo $this->htmlEscape($this->getFormData()->getPhone()) ?>" title="<?php echo $this->__('Phone') ?>" id="solutionpartner:phone" class="input-text required-entry solutionpartner-register-phone" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-6">
                                    <label for="solutionpartner:company_name" class="required"><?php echo $this->__('Company Name') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="company_name" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company Name') ?>" id="solutionpartner:company_name" class="input-text required-entry" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label for="solutionpartner:website" class="required right-l"><?php echo $this->__('Company Website Url') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="website" value="<?php echo $this->htmlEscape($this->getFormData()->getWebsite()) ?>" title="<?php echo $this->__('Company Website Url') ?>" id="solutionpartner:website" class="input-text required-entry" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-md-12">
                                    <label for="solutionpartner:company_logo"><?php echo $this->__('Company Logo') ?></label>
                                    <div class="input-box">
                                        <input type="file" name="company_logo" id="solutionpartner:company_logo" class="input-file" />
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-12">
                                    <label for="solutionpartner:description" class="required right-l"><?php echo $this->__('Description') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <textarea type="text" name="description" value="<?php echo $this->htmlEscape($this->getFormData()->getWebsite()) ?>" title="<?php echo $this->__('Description') ?>" id="solutionpartner:description" class="input-text required-entry description-company" required></textarea>
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-6">
                                    <label for="solutionpartner:address" class="required"><?php echo $this->__('Company Address') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="address" value="<?php echo $this->htmlEscape($this->getFormData()->getAddress()) ?>" title="<?php echo $this->__('Company Address') ?>" id="solutionpartner:address" class="input-text required-entry" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label for="solutionpartner:country" class="required right-l"><?php echo $this->__('Located Country') ?><em>*</em></label>
                                    <div class="input-box">
                                        <select name="country" title="<?php echo $this->__('Located country') ?>" id="solutionpartner:country" class="input-text required-entry">
                                            <?php echo $this->getCountryOption() ?>
                                        </select>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-6">
                                    <label for="solutionpartner:founded_in" class="required"><?php echo $this->__('Founded In') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="founded_in" value="<?php echo $this->htmlEscape($this->getFormData()->getFoundedIn()) ?>" title="<?php echo $this->__('Founded In') ?>" id="solutionpartner:founded_in" class="input-text required-entry" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label for="solutionpartner:certified_dev" class="required right-l"><?php echo $this->__('Certified Developer') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="certified_dev" value="<?php echo $this->htmlEscape($this->getFormData()->getCertifiedDev()) ?>" title="<?php echo $this->__('Certified Developer') ?>" id="solutionpartner:certified_dev" class="input-text required-entry" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-6">
                                    <label for="solutionpartner:number_employees" class="required right-l"><?php echo $this->__('Number Employees') ?><em>*</em></label>
                                    <div class="input-box">
                                        <select name="number_employees" title="<?php echo $this->__('Number Employees') ?>" id="solutionpartner:number_employees" class="input-text required-entry" >
                                            <?php echo $this->getNumberEmployeesOption() ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label for="solutionpartner:industry" class="required right-l"><?php echo $this->__('Industry') ?><em>*</em></label>
                                    <div class="input-box">
                                        <select name="industry" title="<?php echo $this->__('Industry') ?>" id="solutionpartner:industry" class="input-text required-entry" >
                                            <?php echo $this->getIndustryOption() ?>
                                        </select>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-12">
                                    <label for="solutionpartner:project_year" class="required right-l"><?php echo $this->__('How many projects you magento in a year?') ?><em>*</em></label>
                                    <div class="input-layout">
                                        <input type="text" name="project_year" value="<?php echo $this->htmlEscape($this->getFormData()->getProjectYear()) ?>" title="<?php echo $this->__('How many projects you magento in a year?') ?>" id="solutionpartner:project_year" class="input-text required-entry solutionpartner-register-project-year" required />
                                        <span class="highlight"></span>
                                        <span class="bar"></span>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-sm-6">
                                    <label for="solutionpartner:project_size" class="required right-l"><?php echo $this->__('Project Size') ?><em>*</em></label>
                                    <div class="input-box">
                                        <select name="project_size" title="<?php echo $this->__('Project Size') ?>" id="solutionpartner:project_size" class="input-text required-entry" >
                                            <?php echo $this->getProjectSizeOption() ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <label for="solutionpartner:hourly_rate" class="required right-l"><?php echo $this->__('Hourly Rate') ?><em>*</em></label>
                                    <div class="input-box">
                                        <select name="hourly_rate" title="<?php echo $this->__('Hourly Rate') ?>" id="solutionpartner:hourly_rate" class="input-text required-entry" >
                                            <?php echo $this->getHourlyRateOption() ?>
                                        </select>
                                    </div>
                                </div>
                            </li>
                            <li class="row">
                                <div class="col-md-12">
                                    <label for="solutionpartner:term"><?php echo $this->__('Terms and Conditions') ?></label>
                                    <div class="input-box term-condition">
                                        <div name="term" id="solutionpartner:term" class="input-text solutionpartner_term">
                                            <?php echo $this->getTermCondition()?>
                                        </div>
                                        <div class="checkbox-group">
                                            <input id="checkboxcaptcha" class="required-entry" type="checkbox" name="read" value="captcha"/>
                                            <label for="checkboxcaptcha" class="label--checkbox">
                                                <span class="check"></span>
                                                <span class="box-check"></span>
                                                <?php echo $this->__(' I have read and agree to the Terms and Conditions for Partners.*')?>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </li>

                        </ul>
                        <div class="buttons-set" style="margin: 0 0 10px;padding: 10px;">
                            <!--<p class="required" style="text-align:center;"><?php echo $this->__('* Required Fields') ?></p>-->
                            <center>
                                <button type="submit" title="<?php echo $this->__('REGISTER') ?>" class="button" style="float:none;"><span><span><?php echo $this->__('REGISTER') ?></span></span></button>
                            </center>
                        </div>
                    </center>
                </form>
                <script type="text/javascript">
                    //<![CDATA[
                    var dataForm = new VarienForm('solutionpartner-registration-form', false);

                    var count_refresh_captcha = 0;

                    function refreshCaptchaImage(){
                        count_refresh_captcha++;
                        url = '<?php echo $this->getRefreshCaptchaUrl() ?>';
                        $('solutionpartner-captcha-link').hide();
                        $('solutionpartner_captcha_image').src = '<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>';
                        imageCapcha = new Image();
                        imageCapcha.src = '<?php echo  $this->getUrl('solutionpartner/register/captcha') . time() ?>' +'-'+ count_refresh_captcha;
                        $('solutionpartner_captcha_image').src = imageCapcha.src;
                        $('solutionpartner-captcha-link').show();
                    }

                    //]]>
                </script>
            </div>
        </center>
    </div>
    <style type="text/css">
        .form-list input.input-text{height:30px;padding:0 5px;}
        .form-list select{height:32px;padding:5px;}
        .form-list li.wide textarea{padding-left:5px;padding-right:5px;}
        .show_message .messages{
            float: left;
        }

    </style>
<?php else: ?>
<!--    <style type="text/css">-->
<!--        #show-solutionpartner-form, #first-res{-->
<!--            display:none !important;-->
<!--        }-->
<!--    </style>-->
<?php endif ?>